version: "2"

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - gofmt
    - misspell

issues:
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck
